---
name: App-XML-DocBook-Builder
version: 0.0101
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: Build DocBook/XML files.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
requires:
  Class::Accessor: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Long: 2.37
  Pod::Usage: 0
  strict: 0
  warnings: 0
build_requires:
  Test::More: 0
  Test::Trap: 0
provides:
  App::XML::DocBook::Builder:
    file: lib/App/XML/DocBook/Builder.pm
    version: 0.0101
  App::XML::DocBook::Docmake:
    file: lib/App/XML/DocBook/Docmake.pm
    version: 0.0101
  App::XML::DocBook::Docmake::CmdComponent:
    file: lib/App/XML/DocBook/Docmake.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
